module.exports = {
  BaseKonnector: require('./libs/BaseKonnector'),
  errors: require('./libs/errors'),
  log: require('./libs/log'),
  saveFiles: require('./libs/savefiles'),
  saveBills: require('./libs/saveBills'),
  hydrateAndFilter: require('./libs/hydrateAndFilter'),
  solveCaptcha: require('./libs/solveCaptcha'),
  //  updateOrCreate: require('./libs/updateOrCreate'),
  requestFactory: require('./libs/request'),
  signin: require('./libs/signin'),
  submitForm: require('./libs/signin'),
  scrape: require('./libs/scrape'),
  retry: require('bluebird-retry'),
  Document: require('./libs/document'),
  addData: require('./libs/addData'),
  normalizeFilename: require('./libs/normalizeFilename'),
  mkdirp: require('./libs/mkdirp'),
  CookieKonnector: require('./libs/CookieKonnector')
}
